version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: gunicorn --workers=4 config.asgi --log-file - -b 0.0.0.0:8000 -k uvicorn.workers.UvicornWorker --reload
    restart: always
    ports:
    - "8000:8000"
    links:
    - db:db
    - redis:redis
    volumes:
    - ./:/app/src
    env_file:
    - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      BACKEND_HOST: 0.0.0.0
      BACKEND_DB_HOST: backend-db
      BACKEND_DB_PORT: 5432
      BACKEND_DB_USER: backend
      BACKEND_DB_PASS: backend
      BACKEND_DB_BASE: backend
      PGPASSWORD: backend

  db:
    image: postgres:13
    hostname: backend-db
    environment:
      POSTGRES_PASSWORD: "backend"
      POSTGRES_USER: "backend"
      POSTGRES_DB: "backend"
    volumes:
    - backend-db-data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test:
      - CMD
      - pg_isready
      - -U
      - backend
      interval: 2s
      timeout: 3s
      retries: 40
    ports:
    - "9009:5432"

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
    - '6380:6379'
    command: redis-server
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
    volumes:
    - backend-redis-data:/data

  pgweb:
    image: sosedoff/pgweb
    restart: always
    ports:
    - "8081:8081"
    environment:
    - DATABASE_URL=postgres://backend:backend@backend-db:5432/backend?sslmode=disable
    depends_on:
      db:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "10m"

volumes:
  backend-db-data:
    name: backend-db-data
  backend-redis-data:
    name: backend-redis-data
