# Generated by Django 4.1 on 2022-08-14 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0002_alter_comment_question"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Notification",
        ),
    ]
